# Maximilian Thompson
#
# Makefile for project 1 phase 1.

DEBUG = -g -Wall -D_DEBUG

all: mc0 seymour

mc0: mc0.c
	gcc $(DEBUG) mc0.c -o mc0

seymour: seymour.c
	gcc $(DEBUG) seymour.c -o seymour

clean:
	rm -f *.o mc0
